server:
  port: 3344
  
spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wang125631/microservicecloud-config.git
          username: wang125631
          #password: 